export const GAME_CONSTANTS = {
    TIKTOK_STREAM_ACCOUNT:'fenysk',
    QUESTION_DURATION: 45000,
    TOTAL_QUESTION: 30,
    RESTART_DELAY: 60000,
    MAX_QUESTIONS: 50,
    MIN_QUESTIONS: 1,
    LIKE_COUNT_TO_START: 1000,
} as const;