export const GAME_CONSTANTS = {
    TIKTOK_STREAM_ACCOUNT: 'fenysk',
    QUESTION_DURATION: 45,
    TOTAL_QUESTIONS: 30,
    MAX_QUESTIONS: 50,
    MIN_QUESTIONS: 1,
    LIKE_COUNT_TO_START: 1000,
} as const;