import { ChatMessage } from 'src/tiktok/interface/chat.interface';

export class FakeMessages {
    exampleChatMessage1: ChatMessage = { emotes: [], comment: "Métro", userId: "54321", secUid: "sec54321", uniqueId: "unique54321", nickname: "TechGuru", profilePictureUrl: "http://example.com/techguru.jpg", followRole: 0, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-01T00:00:00Z", bioDescription: "Passionate about technology and innovation", profilePictureUrls: ["http://example.com/techguru.jpg"] }, followInfo: { followingCount: 120, followerCount: 220, followStatus: 0, pushStatus: 0 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg54321", createTime: "2023-10-01T00:00:00Z" };
    exampleChatMessage2: ChatMessage = { emotes: [], comment: "Voiture", userId: "67890", secUid: "sec67890", uniqueId: "unique67890", nickname: "CulinaireGourmet", profilePictureUrl: "http://example.com/culinairegourmet.jpg", followRole: 1, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-02T00:00:00Z", bioDescription: "Passionné de cuisine et de gastronomie", profilePictureUrls: ["http://example.com/culinairegourmet.jpg"] }, followInfo: { followingCount: 150, followerCount: 250, followStatus: 1, pushStatus: 1 }, isModerator: true, isNewGifter: true, isSubscriber: true, topGifterRank: 1, gifterLevel: 1, teamMemberLevel: 1, msgId: "msg67890", createTime: "2023-10-02T00:00:00Z" };
    exampleChatMessage3: ChatMessage = { emotes: [], comment: "Métro", userId: "112234", secUid: "sec112234", uniqueId: "unique112234", nickname: "ArtisteCréatif", profilePictureUrl: "http://example.com/artistecreatif.jpg", followRole: 2, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-04T00:00:00Z", bioDescription: "Artiste passionné par la création et l'expression", profilePictureUrls: ["http://example.com/artistecreatif.jpg"] }, followInfo: { followingCount: 250, followerCount: 350, followStatus: 2, pushStatus: 2 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg112234", createTime: "2023-10-04T00:00:00Z" };
    
    exampleChatMessage4: ChatMessage = { emotes: [], comment: "Mandarin", userId: "54321", secUid: "sec54321", uniqueId: "unique54321", nickname: "TechGuru", profilePictureUrl: "http://example.com/techguru.jpg", followRole: 0, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-01T00:00:00Z", bioDescription: "Passionate about technology and innovation", profilePictureUrls: ["http://example.com/techguru.jpg"] }, followInfo: { followingCount: 120, followerCount: 220, followStatus: 0, pushStatus: 0 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg54321", createTime: "2023-10-01T00:00:00Z" };
    exampleChatMessage5: ChatMessage = { emotes: [], comment: "Francais", userId: "67890", secUid: "sec67890", uniqueId: "unique67890", nickname: "CulinaireGourmet", profilePictureUrl: "http://example.com/culinairegourmet.jpg", followRole: 1, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-02T00:00:00Z", bioDescription: "Passionné de cuisine et de gastronomie", profilePictureUrls: ["http://example.com/culinairegourmet.jpg"] }, followInfo: { followingCount: 150, followerCount: 250, followStatus: 1, pushStatus: 1 }, isModerator: true, isNewGifter: true, isSubscriber: true, topGifterRank: 1, gifterLevel: 1, teamMemberLevel: 1, msgId: "msg67890", createTime: "2023-10-02T00:00:00Z" };
    exampleChatMessage6: ChatMessage = { emotes: [], comment: "Espagnol", userId: "112234", secUid: "sec112234", uniqueId: "unique112234", nickname: "ArtisteCréatif", profilePictureUrl: "http://example.com/artistecreatif.jpg", followRole: 2, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-04T00:00:00Z", bioDescription: "Artiste passionné par la création et l'expression", profilePictureUrls: ["http://example.com/artistecreatif.jpg"] }, followInfo: { followingCount: 250, followerCount: 350, followStatus: 2, pushStatus: 2 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg112234", createTime: "2023-10-04T00:00:00Z" };

    exampleChatMessage7: ChatMessage = { emotes: [], comment: "Intouchable", userId: "54321", secUid: "sec54321", uniqueId: "unique54321", nickname: "TechGuru", profilePictureUrl: "http://example.com/techguru.jpg", followRole: 0, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-01T00:00:00Z", bioDescription: "Passionate about technology and innovation", profilePictureUrls: ["http://example.com/techguru.jpg"] }, followInfo: { followingCount: 120, followerCount: 220, followStatus: 0, pushStatus: 0 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg54321", createTime: "2023-10-01T00:00:00Z" };
    exampleChatMessage9: ChatMessage = { emotes: [], comment: "Slumdog Millionaire", userId: "112234", secUid: "sec112234", uniqueId: "unique112234", nickname: "ArtisteCréatif", profilePictureUrl: "http://example.com/artistecreatif.jpg", followRole: 2, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-04T00:00:00Z", bioDescription: "Artiste passionné par la création et l'expression", profilePictureUrls: ["http://example.com/artistecreatif.jpg"] }, followInfo: { followingCount: 250, followerCount: 350, followStatus: 2, pushStatus: 2 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg112234", createTime: "2023-10-04T00:00:00Z" };
    exampleChatMessage8: ChatMessage = { emotes: [], comment: "Slumdog Millionaire", userId: "67890", secUid: "sec67890", uniqueId: "unique67890", nickname: "CulinaireGourmet", profilePictureUrl: "http://example.com/culinairegourmet.jpg", followRole: 1, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-02T00:00:00Z", bioDescription: "Passionné de cuisine et de gastronomie", profilePictureUrls: ["http://example.com/culinairegourmet.jpg"] }, followInfo: { followingCount: 150, followerCount: 250, followStatus: 1, pushStatus: 1 }, isModerator: true, isNewGifter: true, isSubscriber: true, topGifterRank: 1, gifterLevel: 1, teamMemberLevel: 1, msgId: "msg67890", createTime: "2023-10-02T00:00:00Z" };

    exampleChatMessage10: ChatMessage = { emotes: [], comment: "Par quête spirituelle", userId: "54321", secUid: "sec54321", uniqueId: "unique54321", nickname: "TechGuru", profilePictureUrl: "http://example.com/techguru.jpg", followRole: 0, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-01T00:00:00Z", bioDescription: "Passionate about technology and innovation", profilePictureUrls: ["http://example.com/techguru.jpg"] }, followInfo: { followingCount: 120, followerCount: 220, followStatus: 0, pushStatus: 0 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg54321", createTime: "2023-10-01T00:00:00Z" };
    exampleChatMessage11: ChatMessage = { emotes: [], comment: "Par combat", userId: "112234", secUid: "sec112234", uniqueId: "unique112234", nickname: "ArtisteCréatif", profilePictureUrl: "http://example.com/artistecreatif.jpg", followRole: 2, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-04T00:00:00Z", bioDescription: "Artiste passionné par la création et l'expression", profilePictureUrls: ["http://example.com/artistecreatif.jpg"] }, followInfo: { followingCount: 250, followerCount: 350, followStatus: 2, pushStatus: 2 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg112234", createTime: "2023-10-04T00:00:00Z" };
    exampleChatMessage12: ChatMessage = { emotes: [], comment: "Par quête spirituelle", userId: "67890", secUid: "sec67890", uniqueId: "unique67890", nickname: "CulinaireGourmet", profilePictureUrl: "http://example.com/culinairegourmet.jpg", followRole: 1, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-02T00:00:00Z", bioDescription: "Passionné de cuisine et de gastronomie", profilePictureUrls: ["http://example.com/culinairegourmet.jpg"] }, followInfo: { followingCount: 150, followerCount: 250, followStatus: 1, pushStatus: 1 }, isModerator: true, isNewGifter: true, isSubscriber: true, topGifterRank: 1, gifterLevel: 1, teamMemberLevel: 1, msgId: "msg67890", createTime: "2023-10-02T00:00:00Z" };

    exampleChatMessage13: ChatMessage = { emotes: [], comment: "Leonard de vinci", userId: "54321", secUid: "sec54321", uniqueId: "unique54321", nickname: "TechGuru", profilePictureUrl: "http://example.com/techguru.jpg", followRole: 0, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-01T00:00:00Z", bioDescription: "Passionate about technology and innovation", profilePictureUrls: ["http://example.com/techguru.jpg"] }, followInfo: { followingCount: 120, followerCount: 220, followStatus: 0, pushStatus: 0 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg54321", createTime: "2023-10-01T00:00:00Z" };
    exampleChatMessage14: ChatMessage = { emotes: [], comment: "Leonard de vinci", userId: "112234", secUid: "sec112234", uniqueId: "unique112234", nickname: "ArtisteCréatif", profilePictureUrl: "http://example.com/artistecreatif.jpg", followRole: 2, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-04T00:00:00Z", bioDescription: "Artiste passionné par la création et l'expression", profilePictureUrls: ["http://example.com/artistecreatif.jpg"] }, followInfo: { followingCount: 250, followerCount: 350, followStatus: 2, pushStatus: 2 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg112234", createTime: "2023-10-04T00:00:00Z" };
    exampleChatMessage15: ChatMessage = { emotes: [], comment: "Leonard de vinci", userId: "67890", secUid: "sec67890", uniqueId: "unique67890", nickname: "CulinaireGourmet", profilePictureUrl: "http://example.com/culinairegourmet.jpg", followRole: 1, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-02T00:00:00Z", bioDescription: "Passionné de cuisine et de gastronomie", profilePictureUrls: ["http://example.com/culinairegourmet.jpg"] }, followInfo: { followingCount: 150, followerCount: 250, followStatus: 1, pushStatus: 1 }, isModerator: true, isNewGifter: true, isSubscriber: true, topGifterRank: 1, gifterLevel: 1, teamMemberLevel: 1, msgId: "msg67890", createTime: "2023-10-02T00:00:00Z" };

    exampleChatMessage16: ChatMessage = { emotes: [], comment: "9.58 secondes", userId: "54321", secUid: "sec54321", uniqueId: "unique54321", nickname: "TechGuru", profilePictureUrl: "http://example.com/techguru.jpg", followRole: 0, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-01T00:00:00Z", bioDescription: "Passionate about technology and innovation", profilePictureUrls: ["http://example.com/techguru.jpg"] }, followInfo: { followingCount: 120, followerCount: 220, followStatus: 0, pushStatus: 0 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg54321", createTime: "2023-10-01T00:00:00Z" };
    exampleChatMessage17: ChatMessage = { emotes: [], comment: "9.58 secondes", userId: "112234", secUid: "sec112234", uniqueId: "unique112234", nickname: "ArtisteCréatif", profilePictureUrl: "http://example.com/artistecreatif.jpg", followRole: 2, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-04T00:00:00Z", bioDescription: "Artiste passionné par la création et l'expression", profilePictureUrls: ["http://example.com/artistecreatif.jpg"] }, followInfo: { followingCount: 250, followerCount: 350, followStatus: 2, pushStatus: 2 }, isModerator: false, isNewGifter: false, isSubscriber: false, topGifterRank: null, gifterLevel: 0, teamMemberLevel: 0, msgId: "msg112234", createTime: "2023-10-04T00:00:00Z" };
    exampleChatMessage18: ChatMessage = { emotes: [], comment: "9.58 secondes", userId: "67890", secUid: "sec67890", uniqueId: "unique67890", nickname: "CulinaireGourmet", profilePictureUrl: "http://example.com/culinairegourmet.jpg", followRole: 1, userBadges: [], userSceneTypes: [], userDetails: { createTime: "2023-10-02T00:00:00Z", bioDescription: "Passionné de cuisine et de gastronomie", profilePictureUrls: ["http://example.com/culinairegourmet.jpg"] }, followInfo: { followingCount: 150, followerCount: 250, followStatus: 1, pushStatus: 1 }, isModerator: true, isNewGifter: true, isSubscriber: true, topGifterRank: 1, gifterLevel: 1, teamMemberLevel: 1, msgId: "msg67890", createTime: "2023-10-02T00:00:00Z" };
}